var num1=8;
var num2=7;
var sum,mul=1;
sum=num1+num2;
mul=num1*num2;

console.log("sum is:+",sum);
alert("mul is:"+mul);
document.writeln("num1 is:",+num1);
document.writeln("num2 is:",+num2);

document.getElementById("multiplication").append=56;

var studentid="101";
var sid=101;

document.write(parseInt(studentid)+sid);

document.write( "          " );
document.write(studentid == sid);// content checking

document.write( "          " );

document.write( typeof studentid);

document.write( "          " );
document.write( typeof sid);

document.write( "          " );
document.write(studentid === sid);// datatype
